Downgrade dependencies
... to get readthedocs working

ERROR: Cannot install ...

The conflict is caused by:
    The user requested importlib-metadata==4.0.1
    importlib-resources 1.5.0 depends on importlib-metadata; python_version < "3.8"
    pluggy 0.13.1 depends on importlib-metadata>=0.12; python_version < "3.8"
    pytest 6.2.3 depends on importlib-metadata>=0.12; python_version < "3.8"
    tox 3.23.0 depends on importlib-metadata>=0.12; python_version < "3.8"
    virtualenv 20.0.23 depends on importlib-metadata<2 and >=0.12; python_version < "3.8"